dist: trusty
sudo: required
services:
- docker
install: true
addons:
  apt:
    packages:
    - docker-ce
    - git
before_install:
- make update-dependencies
script:
- make test-alpine
deploy:
- provider: script
  script: make -w release-ci
  skip_cleanup: true
notifications:
  slack:
    secure: lVZrP755pdWGGocYA+lTaiE3Qrd7qBFyCpERj+siu5coTXuDCwWlO176DSO7MH4jveNKjL/SnHGtNJzTYXesxMgxOw2DTp0XBi2lXbys/Pp762cpGLJa8FR6K2t1m/IwJwqE4Ze0vlpxi06TbQa99Yv3d2s+AnWlzR8BOMClAWTkN2o6fNwH1pXIHEKHF3ggN9eltoG+FDWHJPBh2G5Oofg2R3GND3Nqb696XwUUiZYmyjdRREMWcd1XwfDO+CsaDjKCYB3ZXL47MGhDZ/uM43uTTpbZ2ZrCGxFAdGgBxzKW2WR1nSUkI+ox7lAXpfRuSD3I1dnTWYG6kpCuTiZLl4XyqFaziQ103S2Vk0wdguxN3n6TLu88xDK8QuMyMOif0NF0BB4OSd0mRkM2GvsSfSM4x4B1vI9dCBlWOV5GfIOfjqfNVGMvB19sAvpr8+8shmXDvT5/v3ZbdqCl2kGGLTS5wqdJOW8llawkShzJ+LcLO0i20m9n9H2ntsRuBXcjsfmQxirQ0e4r3SW7Dg817Xjzgk1wofw09jq7qxXo8Xh7n/UKENVbxGa2w0PNkNPP/edPYGaW5X1Zj1pwnJ2+rPDDvVgD3gmV06DrL0aq8DiRca51beCuEi3QFKHAORDprz2zDF38JkfKuBOK6Nv2LlXOBlpgFqqmjiSbi1SRvV4=
