dist: trusty
sudo: required
services:
- docker
install: true
addons:
  apt:
    packages:
    - docker-ce
    - git
before_install:
- make update-dependencies
script:
- make test-alpine
deploy:
- provider: script
  script: make -w release-ci
  skip_cleanup: true
notifications:
  slack:
    secure: MYygcOGc2g5Um8TGDN32jMbLt4Y9bZ71Mw+WFhTzkgqnxWlk/4f0F7aa1Ln2JYJYwrSM6qZkLUklf8J8n+aLdmUJWjeATzXVGlAUiZAxNuNeunOxU2bPmysC9LF0x7+x6cMGGj0TeMrOjVePeZKEddczk2yLnneaOIJH6D/lJkHu2d9ZR3iuE8I+2jpYqEvUxSET1TBV7VulZsML2pKbLetNoa3VgjlKotsnjIII1tfeFxq6a2QX4+ws+fS5mKUdWecvF33ZT282rJvc7JGhySxGHj+dsi4EE5Kr8T0Pp9q7EL2VUrDR6mWKZhmsegP8gaqz4dYsPbrDhjCWbwusT+Z66u21cGZnVfW73zZsu+SNiRHdT8Ar0akyjUZOMN82J1R/y9aNzg/YBwasRMNKl1xzy/zr+aa0kQb/aqo5IygkyIXIUKj44MoFEoeKw1GOemfamMWPEdgCTpHJdBrvFSKzkZ14halsLuZEINVvg0SxRB9py/nTXrlotggK3thGw6yitNsgTODCzVPaoiK3a/j/EIef5xtQhDt12pun1Xtfc+9adwGpvAzrTv1aqzKoVQlZlMrgWC0j7+geq6ONhH8l0WKe9RubZjaxQXmKbDFcmnoZcQbdNAV1IOA4MUKbP2V0G4HYK8t7jNx9CasS0I1v7hiz3n9dOnhMlCjCifA=
